version: '3.4'
services:
  elasticsearch:
    image: elasticsearch:6.8.23
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - cluster.name=conductor
      - transport.host=0.0.0.0
      - transport.publish_host=192.168.186.166
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - bootstrap.memory_lock=true
    volumes:
      - esdata-conductor:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9300'
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  kibana:
    container_name: kibana
    restart: always
    image: kibana:6.8.23
    # volumes:
    #   - /home/elk/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      # - TZ=Asia/Shanghai
      - http.host=0.0.0.0
      - elasticsearch.url=http://elasticsearch:9200
      - elasticsearch.hosts=http://elasticsearch:9200
      - xpack.monitoring.enabled=false
      #- xpack.monitoring.ui.container.elasticsearch.enabled=true
      #- monitoring.ui.container.elasticsearch.enabled=true
      #- elasticsearch.username=elastic
      #- elasticsearch.password=aa111111
      #- xpack.security.enabled=true
    ports:
      - 5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy

  rabbit:
    image: rabbitmq:3.9-management
    restart: unless-stopped
    hostname: rabbit
    container_name: "wycs_rabbitmq3.9"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_ERLANG_COOKIE='takeMyCookies'
      - RABBITMQ_SECURE_PASSWORD=yes
    volumes:
      - rabbitmq-conductor:/var/lib/rabbitmq/mnesia

volumes:
  esdata-conductor:
  rabbitmq-conductor:
